
    import React from 'react';
    import Button from '@/app/components/Button';
    import SectionComponents from '@/app/components/Section';
    const { Container, Section } = SectionComponents;
    import ColumnComponents from '@/app/components/Columns';
    const { Columns, Column  } = ColumnComponents;
    import PropertySearch from '@/app/components/PropertySearch';
    import Text from '@/app/components/Text';
    import Navigation from '@/app/components/Navigation';
    import '../styles/globals.css';
 

    const index = () => (
      <>
      <Navigation
  apiUrl="http://localhost:8081/api"
  firebaseUid="QORrMqFligdY0iugUk3FuTEEuUR2"
/>
<>
  <Section
    attachmentValue="scroll"
    backgroundColor="transparent"
    backgroundImage="https://firebasestorage.googleapis.com/v0/b/guesthouz-user-authentication.appspot.com/o/QORrMqFligdY0iugUk3FuTEEuUR2%2FMedia%20Library%2Fcape-coral.png?alt=media&token=1d8095e0-d94e-41cd-a453-7d3bf3501a0c"
    bottomMarginUnitValue="px"
    bottomMarginValue="0"
    bottomPaddingUnitValue="px"
    bottomPaddingValue="80"
    displaySizeValue="auto"
    leftMarginUnitValue="px"
    leftMarginValue="0"
    leftPaddingUnitValue="px"
    leftPaddingValue="0"
    marginAllUnitValue="px"
    marginAllValue="0"
    paddingAllUnit="px"
    paddingAllUnitValue="px"
    paddingAllValue=""
    positionValue="center center"
    repeatValue="no-repeat"
    rightMarginUnitValue="px"
    rightMarginValue="0"
    rightPaddingUnitValue="px"
    rightPaddingValue="0"
    topMarginUnitValue="px"
    topMarginValue="0"
    topPaddingUnitValue="px"
    topPaddingValue="80"
  >
    <Container>
      <Columns>
        <Column
          VerticalAlign="center"
          align="start"
          attachmentValue="scroll"
          backgroundColor="rgba(255, 255, 255, 1)"
          bottomMarginUnitValue="px"
          bottomMarginValue="0"
          bottomPaddingUnitValue="px"
          bottomPaddingValue="60"
          displayValue="block"
          leftMarginUnitValue="px"
          leftMarginValue="0"
          leftPaddingUnitValue="px"
          leftPaddingValue="60"
          marginAllUnitValue="px"
          marginAllValue="0"
          paddingAllUnit="px"
          paddingAllUnitValue="px"
          paddingAllValue="60"
          positionValue="center center"
          repeatValue="no-repeat"
          rightMarginUnitValue="px"
          rightMarginValue="0"
          rightPaddingUnitValue="px"
          rightPaddingValue="60"
          style={{
            flex: 1
          }}
          topMarginUnitValue="px"
          topMarginValue="0"
          topPaddingUnitValue="px"
          topPaddingValue="60"
        >
          <Text
            attachmentValue="scroll"
            backgroundColor="transparent"
            bottomMarginUnitValue="px"
            bottomMarginValue="10"
            bottomPaddingUnitValue="px"
            bottomPaddingValue="0"
            color="rgba(213, 109, 34, 1)"
            displaySizeValue="auto"
            fontFamily="Lato"
            fontSizeUnit="px"
            fontSizeValue="16"
            fontWeightValue="700"
            leftMarginUnitValue="px"
            leftMarginValue="0"
            leftPaddingUnitValue="px"
            leftPaddingValue="0"
            lineHeightUnit="px"
            lineHeightValue=""
            marginAllUnitValue="px"
            marginAllValue=""
            paddingAllUnit="px"
            paddingAllUnitValue="px"
            paddingAllValue="0"
            positionValue="center center"
            repeatValue="no-repeat"
            rightMarginUnitValue="px"
            rightMarginValue="0"
            rightPaddingUnitValue="px"
            rightPaddingValue="0"
            spacingUnit="px"
            spacingValue=""
            text="SUNNY VILLA"
            textAlign="left"
            textDecorationValue="none"
            topMarginUnitValue="px"
            topMarginValue="0"
            topPaddingUnitValue="px"
            topPaddingValue="0"
          />
          <Text
            attachmentValue="scroll"
            backgroundColor="transparent"
            bottomMarginUnitValue="px"
            bottomMarginValue="15"
            bottomPaddingUnitValue="px"
            bottomPaddingValue="0"
            color="rgba(51, 51, 51, 1)"
            displaySizeValue="auto"
            fontFamily="Roboto"
            fontSizeUnit="px"
            fontSizeValue="52"
            fontWeightValue="500"
            leftMarginUnitValue="px"
            leftMarginValue="0"
            leftPaddingUnitValue="px"
            leftPaddingValue="0"
            lineHeightUnit="px"
            lineHeightValue=""
            marginAllUnitValue="px"
            marginAllValue=""
            paddingAllUnitValue="px"
            paddingAllValue="0"
            positionValue="center center"
            repeatValue="no-repeat"
            rightMarginUnitValue="px"
            rightMarginValue="0"
            rightPaddingUnitValue="px"
            rightPaddingValue="0"
            spacingUnit="px"
            spacingValue=""
            text="Welcome to our beautiful villas"
            textAlign="left"
            textDecorationValue="none"
            topMarginUnitValue="px"
            topMarginValue="0"
            topPaddingUnitValue="px"
            topPaddingValue="0"
          />
          <Text
            attachmentValue="scroll"
            backgroundColor="transparent"
            bottomMarginUnitValue="px"
            bottomMarginValue="25"
            bottomPaddingUnitValue="px"
            bottomPaddingValue="0"
            color="#000"
            displaySizeValue="auto"
            fontFamily="Roboto"
            fontSizeUnit="px"
            fontSizeValue="18"
            fontWeightValue="400"
            leftMarginUnitValue="px"
            leftMarginValue="0"
            leftPaddingUnitValue="px"
            leftPaddingValue="0"
            lineHeightUnit="em"
            lineHeightValue="1.7"
            marginAllUnitValue="px"
            marginAllValue=""
            paddingAllUnitValue="px"
            paddingAllValue="0"
            positionValue="center center"
            repeatValue="no-repeat"
            rightMarginUnitValue="px"
            rightMarginValue="0"
            rightPaddingUnitValue="px"
            rightPaddingValue="0"
            spacingUnit="px"
            spacingValue=""
            text="We use the text and images from your current property listings on Airbnb or VRBO to save you time while building your site. Request changes anytime!"
            textAlign="left"
            textDecorationValue="none"
            topMarginUnitValue="px"
            topMarginValue="0"
            topPaddingUnitValue="px"
            topPaddingValue="0"
          />
          <Button
            backgroundColor="#8AA09D"
            bottomPaddingUnitValue="px"
            bottomPaddingValue="12"
            color="#fff"
            fontFamily="Roboto"
            fontSizeUnit="px"
            fontSizeValue="16"
            fontWeightValue="400"
            leftPaddingUnitValue="px"
            leftPaddingValue="20"
            paddingAllUnit="px"
            paddingAllUnitValue="px"
            paddingAllValue=""
            rightPaddingUnitValue="px"
            rightPaddingValue="20"
            size="small"
            text="BOOK YOUR STAY"
            topPaddingUnitValue="px"
            topPaddingValue="12"
          />
        </Column>
        <Column
          VerticalAlign="center"
          align="start"
          attachmentValue="scroll"
          backgroundColor="rgba(255, 255, 255, 0)"
          bottomMarginUnitValue="px"
          bottomMarginValue="0"
          bottomPaddingUnitValue="px"
          bottomPaddingValue="0"
          displayValue="block"
          leftMarginUnitValue="px"
          leftMarginValue="0"
          leftPaddingUnitValue="px"
          leftPaddingValue="0"
          marginAllUnitValue="px"
          marginAllValue="0"
          paddingAllUnitValue="px"
          paddingAllValue="0"
          positionValue="center center"
          repeatValue="no-repeat"
          rightMarginUnitValue="px"
          rightMarginValue="0"
          rightPaddingUnitValue="px"
          rightPaddingValue="0"
          style={{
            flex: 1
          }}
          topMarginUnitValue="px"
          topMarginValue="0"
          topPaddingUnitValue="px"
          topPaddingValue="0"
        />
      </Columns>
    </Container>
  </Section>
  <Section
    attachmentValue="scroll"
    backgroundColor="#8AA09D"
    bottomMarginUnitValue="px"
    bottomMarginValue="0"
    bottomPaddingUnitValue="px"
    bottomPaddingValue="10"
    displaySizeValue="auto"
    leftMarginUnitValue="px"
    leftMarginValue="0"
    leftPaddingUnitValue="px"
    leftPaddingValue="0"
    marginAllUnitValue="px"
    marginAllValue="0"
    paddingAllUnitValue="px"
    paddingAllValue=""
    positionValue="center center"
    repeatValue="no-repeat"
    rightMarginUnitValue="px"
    rightMarginValue="0"
    rightPaddingUnitValue="px"
    rightPaddingValue="0"
    topMarginUnitValue="px"
    topMarginValue="0"
    topPaddingUnitValue="px"
    topPaddingValue="10"
  >
    <Container>
      <Columns>
        <Column
          VerticalAlign="center"
          align="start"
          attachmentValue="scroll"
          backgroundColor="#b2b2b266"
          bottomMarginUnitValue="px"
          bottomMarginValue="0"
          bottomPaddingUnitValue="px"
          bottomPaddingValue="0"
          displayValue="block"
          leftMarginUnitValue="px"
          leftMarginValue="0"
          leftPaddingUnitValue="px"
          leftPaddingValue="0"
          marginAllUnitValue="px"
          marginAllValue="0"
          paddingAllUnitValue="px"
          paddingAllValue="0"
          positionValue="center center"
          repeatValue="no-repeat"
          rightMarginUnitValue="px"
          rightMarginValue="0"
          rightPaddingUnitValue="px"
          rightPaddingValue="0"
          style={{
            flex: 1
          }}
          topMarginUnitValue="px"
          topMarginValue="0"
          topPaddingUnitValue="px"
          topPaddingValue="0"
        >
          <PropertySearch />
        </Column>
        <Column
          VerticalAlign="center"
          align="start"
          attachmentValue="scroll"
          backgroundColor="#b2b2b266"
          bottomMarginUnitValue="px"
          bottomMarginValue=""
          bottomPaddingUnitValue="px"
          bottomPaddingValue="0"
          displayValue="block"
          leftMarginUnitValue="px"
          leftMarginValue=""
          leftPaddingUnitValue="px"
          leftPaddingValue=""
          marginAllUnitValue="px"
          marginAllValue="0"
          paddingAllUnitValue="px"
          paddingAllValue="0"
          positionValue="center center"
          repeatValue="no-repeat"
          rightMarginUnitValue="px"
          rightMarginValue=""
          rightPaddingUnitValue="px"
          rightPaddingValue=""
          style={{
            flex: 1
          }}
          topMarginUnitValue="px"
          topMarginValue=""
          topPaddingUnitValue="px"
          topPaddingValue="0"
        />
      </Columns>
    </Container>
  </Section>
</>
      </>
    );

    export default index;
  